### ISSUE TITLE
Rename interface for consistence?

### ISSUE THREAD

**Issue by Giuseppe-Mazzapica** [container-interop/service-provider#19]
Before someone posts [this article](http://verraes.net/2013/09/sensible-interfaces/) as answer, I want to say that I'm aware of it.

I also have my own opinion, but it is irrelevant here.

This is all about consistence.

`ContainerInterface` uses the suffix `Interface`, I think that for consistence would be nice if the service provider interface would be named `ServiceProviderInterface`.

**Comment by moufmouf** [comment]
As much as I hate it, I must admit you have a point.

If this has a chance of becoming a PSR one day, we will have to respect the PSR naming conventions, including the dreadful first rule:

> Interfaces MUST be suffixed by Interface: e.g. Psr\Foo\BarInterface.

See: http://www.php-fig.org/bylaws/psr-naming-conventions/

@mnapoli : I know you hate this. Shall we make the change now or wait for a proper PSR proposal?

**Comment by mnapoli** [comment]
There is also this recent thread: https://groups.google.com/forum/#!topic/php-fig/Zgfd0gHUUoc This might get removed from the bylaws. What should we do?

**Comment by moufmouf** [comment]
Shall we keep this issue open until the issue is settled with the PHP-FIG?

**Comment by MidnightDesign** [comment]
👍 Consistency

**Comment by gbprod** [comment]
:+1: I think we should be consistant. I can make a Pull Request with this changes if you want ;)

**Comment by moufmouf** [comment]
Closed by #34
