### ISSUE TITLE
Project template

### ISSUE THREAD

**Issue by moufmouf** [container-interop/service-provider#32]
While creating service-providers, I found myself doing over and over the same thing:
- creating a composer file
- creating the service provider
- creating a README
- ...

There is clearly some room for a template project. I started a "template" project here: https://github.com/thecodingmachine/service-provider-template

I'd be curious to gather some feedback from you guys.
Is it good enough? What would you do differently?

**Comment by mindplay-dk** [comment]
Closing this, as it does not directly relate to the PSR.
