### ISSUE TITLE
Allow Multiple Extensions

### ISSUE THREAD

**Issue by XedinUnknown** [container-interop/service-provider#47]
Hi! Thanks for the latest changes.

## The Problem
Cannot supply multiple extensions for same service.

## Possible Cause
`ServiceProviderInterface#getExtensions()` is a map of service name to callable. Because it's a map, it's not possible to add multiple "extension callbacks" for the same service, as the next value would override the previous one.

## Suggested Solution
Have `ServiceProviderInterface#getExtensions()` return a map of service names to **lists** of callbacks, `array<string, array<int, callable>>`.

## Remarks

Now that I'm set on using this once again useful standard, I'm trying to create an implementation that is much simpler than what I had before, and with added features. As I started outlining the implementation, I realized that there is what seems to me a conceptual flaw in `ServiceProviderInterface#getExtensions()`: there can only be one extension for a service. Meanwhile, in the real world this is not true, and that's kind of the reason for having extensions: each "module" can provide their own extensions.

That conceptual problem leads to real implementation problems, making it impossible to create a composite service provider. I would really like to be able to do this, because it would allow for my modular architecture to be even further simplified, as well as to simplify the container implementation itself: no longer would it have to cater for multiple providers, but could consume a provider hierarchy without being explicitly aware of it.

**Comment by XedinUnknown** [comment]
After some effort, I realized that this is not impossible: I can merge extension callbacks recursively into one callback, and expose that. Still, not sure this is the best way, both conceptually, and technically.

**Comment by mindplay-dk** [comment]
> After some effort, I realized that this is not impossible: I can merge extension callbacks recursively into one callback, and expose that. Still, not sure this is the best way, both conceptually, and technically.

This was exactly my thinking.

I don't think there's anything wrong with that. Conceptually, and technically, one service provider makes one change to one service - whether that underlying change consists of one more changes in an implementation detail of the service provider, and not something that needs to affect the consumer.

In keeping with the effort to find the "lowest common denominator" required for interoperability, I am closing this issue - if you feel this needs further discussion, please open a thread in Discussions.
