### ISSUE TITLE
Q: Null-service rationale

### ISSUE THREAD

**Issue by samdark** [container-interop/service-provider#55]
I wonder what is rationale behind "A factory/extension can return null"?

1. What's the use case of container having a service by name "x" but returning `null`?
2. Extension is meant replace existing service with a modified version. Does returning `null` mean something like "kill a given service"? What's the use case for it?

**Comment by yiiliveext** [comment]
3. What's the use case for setting the `service` parameter to null. In my opinion, an extension is something that extends some existing service, if the service doesn't exist container should throw an exception.

**Comment by KorvinSzanto** [comment]
> What's the use case of container having a service by name \"x\" but returning null?

I imagine the idea is the factory can optionally return a service. Imagine a factory for a redis connection that only returns if the redis extension is enabled.

> Extension is meant replace existing service with a modified version. Does returning null mean something like \"kill a given service\"? What's the use case for it?

This does feel a little funky to me, but the functional effect is allowing an extension to gate access to a service for whatever reason it might have.

**Comment by samdark** [comment]
> I imagine the idea is the factory can optionally return a service. Imagine a factory for a redis connection that only returns if the redis extension is enabled.

Likely that was an idea but the following is very confusing:

> From the main document: A factory/extension can return null. In this case, the container consuming the service provider MUST register a service that is null.

Why returning `null` should register a "null-service"? Ignoring it in this case sounds way more logical.

**Comment by KorvinSzanto** [comment]
> Why returning null should register a \"null-service\"? Ignoring it in this case sounds way more logical.

Agreed

**Comment by mindplay-dk** [comment]
I actually do recall why it was described this way - if you'd like to see the explanation, I've clarified this in the draft PSR [here](https://github.com/mindplay-dk/service-provider/pull/1/commits/0635bec91de571d62e88f80e852bec2d7b2f6809?diff=split&w=0).
