### ISSUE TITLE
Integration with Puli?

### ISSUE THREAD

**Issue by moufmouf** [container-interop/service-provider#6]
Service providers are a natural match for Puli's discovery system. Indeed, service providers are static, and Puli is capable of discovering classes.

Should we consider adding a `puli.json` file that declares a binding type on classes implementing the ServiceProviderInterface?
That would allow packages implementing the ServiceProviderInterface to also register the class for Puli discovery.

If we don't want to put Puli specific files in this repository, should we consider adding another repository to container-interop that adds this Puli layer? (for instance: service-provider-puli-bindings)

**Comment by mnapoli** [comment]
I of course think this package should be decoupled from Puli, but I don't see a big issue having a `puli.json` in here honestly, it's not like it would do anything if not used. I would be OK with it.

**Comment by mnapoli** [comment]
Closed by #8
